# Generated by Django 3.2 on 2021-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floorplan/'),
        ),
        migrations.AddField(
            model_name='house',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
