# Generated by Django 3.2 on 2021-07-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20210711_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='floor_plan',
        ),
    ]
