# Generated by Django 3.2 on 2021-07-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_remove_house_floor_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='area',
        ),
        migrations.RemoveField(
            model_name='house',
            name='video',
        ),
    ]
