# Generated by Django 3.2 on 2021-07-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20210712_0843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Housee',
        ),
    ]
